apiVersion: v1
kind: Service
metadata:
  name: weatherly-frontend
  namespace: weatherly
spec:
  selector:
    app: weatherly-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
