apiVersion: v1
kind: Service
metadata:
  name: weatherly-mongodb
  namespace: weatherly
spec:
  selector:
    app: weatherly-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
