apiVersion: v1
kind: Service
metadata:
  name: weatherly-backend
  namespace: weatherly
spec:
  selector:
    app: weatherly-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
